export const menuItems = [
  {
    name: 'Inicio',
    link: '/',
  },
  {
    name: '¿Qué es un fractal?',
    link: '/fractal',
  },
  {
    name: 'Copo de nieve de Koch',
    link: '/koch',
  },
  {
    name: 'Triángulo de Sierpińsky',
    link: '/sierpinsky',
  },
  {
    name: 'Diagrama de bifurcación logística',
    link: '/logistic-map',
  },
  {
    name: 'Conjunto de Mandelbrot',
    link: '/mandelbrot',
  },
  {
    name: 'Ejemplo canvas',
    link: '/sample',
  },
  {
    name: 'Bibliografía',
    link: '/bibliography',
  },
  { name: 'Sierpinski non-symmetry (1)' },
  { name: 'Sierpinski random (1)' },
  { name: 'Buddhabrot (1)' },
  { name: 'Cellular (4)' },
  { name: 'Chaos Game (3)' },
  { name: 'Coast (3)' },
  { name: 'Dejong (1)' },
  { name: 'DLA (4)' },
  { name: 'IFS (3)' },
  { name: 'IFS Random (1)' },
  { name: 'Island (1)' },
  { name: 'Julia (2)' },
  { name: 'Lighting (1)' },
  { name: 'Lindenmayer (2)' },
  { name: 'Lorenz (2)' },
  { name: 'Pickover (1)' },
  { name: 'Population (2)' },
  { name: 'Pytree (3)' },
  { name: 'Rossler (1)' },
  { name: 'SSF (5)' },
  { name: 'Transform (1)' },
  { name: 'Tree (4)' },
];
